// Replace these placeholder URLs with your own files in public/images.
const photo = id => `https://images.pexels.com/photos/${id}/pexels-photo-${id}.jpeg?auto=compress&cs=tinysrgb&w=1400&q=80`;
export const portfolioImages = {
  heroMain: photo(3062553),
  heroSecondary: photo(8100060),
  competition: photo(7780108),
};
export const productionScenes = [
  { id: 'events', label: '01 / SCHOOL EVENTS', title: 'Make events happen.', description: 'Set up PA systems, announce on stage, and help organise school events. Work together from the first sound check to the final announcement.', image: photo(14540966), video: '', alt: 'Placeholder: microphone and audio mixing console' },
  { id: 'production', label: '02 / MEDIA PRODUCTION', title: 'Film. Edit. Design.', description: 'Record school events, turn footage into videos, and design posters and graphics. Make work the whole school can see.', image: photo(13812425), video: '', alt: 'Placeholder: camera operator working on a production' },
  { id: 'projects', label: '03 / WORKSHOPS & COMPETITIONS', title: 'Learn and take part.', description: 'Build new skills in workshops and projects. Take part in media competitions within school and with other schools.', image: photo(7780108), video: '', alt: 'Placeholder: audience taking part in an event' },
];
export const creativeTeams = [
  { id: 'sound', name: 'PA Systems & Sound', description: 'Help every voice reach the audience.', activities: ['Set up microphones and speakers for school events.', 'Check sound levels before the event starts.', 'Learn to operate a PA system and sound mixer.'], suitability: 'Try this if you enjoy working with equipment and want to learn how sound works.', image: photo(14540966), imageAlt: 'Placeholder: microphone and sound equipment' },
  { id: 'announcing', name: 'Announcing', description: 'Bring school events to life on the microphone.', activities: ['Make announcements at assemblies and events.', 'Introduce speakers and performances.', 'Practise clear speaking and event presenting.'], suitability: 'Try this if you enjoy speaking or want to build your confidence.', image: photo(7780108), imageAlt: 'Placeholder: audience at a live event' },
  { id: 'design', name: 'Graphic Design', description: 'Create posters and graphics for the school.', activities: ['Design posters for school events.', 'Choose clear colours, fonts and layouts.', 'Prepare graphics for projects and announcements.'], suitability: 'Try this if you enjoy drawing, arranging pictures or working with colours.', image: photo(8100060), imageAlt: 'Placeholder: creative workstation' },
  { id: 'editing', name: 'Video Editing', description: 'Turn recorded clips into a finished video.', activities: ['Choose the best clips from an event.', 'Cut and arrange footage in order.', 'Add titles, music and sound.'], suitability: 'Try this if you enjoy videos and want to learn how they are put together.', image: photo(8100060), imageAlt: 'Placeholder: video editing workstation' },
  { id: 'video', name: 'Videography', description: 'Capture school events through a camera.', activities: ['Practise steady camera shots.', 'Record school events and special moments.', 'Plan the angles and moments to film.'], suitability: 'Try this if you like cameras and noticing what is happening around you.', image: photo(13812425), imageAlt: 'Placeholder: camera operator filming' },
  { id: 'events', name: 'Event Management', description: 'Help an event run smoothly from start to finish.', activities: ['Help plan the tasks for an event.', 'Coordinate with the sound, media and announcing teams.', 'Support the team during school and special events.'], suitability: 'Try this if you enjoy organising things and working with other people.', image: photo(7780108), imageAlt: 'Placeholder: school-style event audience' },
  { id: 'projects', name: 'Workshops & Projects', description: 'Learn a skill, then put it into practice.', activities: ['Take part in media workshops.', 'Practise what you learn with other members.', 'Work together on media unit projects.'], suitability: 'Try this if you are curious and enjoy learning by doing.', image: photo(3062553), imageAlt: 'Placeholder: production equipment for practical learning' },
  { id: 'competitions', name: 'Media Competitions', description: 'Challenge yourself and represent your school.', activities: ['Join media competitions held within school.', 'Prepare entries and practise with the team.', 'Take part in competitions with other schools.'], suitability: 'Try this if you want to improve a skill and test it in a competition.', image: photo(7780108), imageAlt: 'Placeholder: participants at a media event' },
];